### ISSUE TITLE
Permalinks Case

### ISSUE THREAD

**Issue by allejo** [stakx-io/stakx#9]
Permalinks can be explicitly written or can be generated from variables. When permalinks are generated from variables such as post titles, they often will have some upper case letters. Now, my question is whether or not permalinks should always be converted to lower case, as most of the web does follow this convention, but should upper case letters even be allowed in URLs?

```
---
title: Upper Case Title
permalink: /posts/%title
---
```

generates:

```
/posts/Upper-Case-Title/
```

**Comment by davidshower** [comment]
I vote to have them converted to all lower case in the URL.
